[model]
model_types = ["MLPDiamond", "LSTM", "GRU"]

# define the search space for a grid search for hyperparameter tuning
[grid]
all_rf_estimators = [10, 50, 100, 200, 500]
all_rf_subsamples = [0.5, 0.7, 0.9, 1.0]
all_rf_sample_by_nodes = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
all_lags = [12, 3, 5, 7, 9]
all_lr = [ 0.01, 0.001, 0.005, 0.0001]
all_batch_size = [9, 18, 36, 72, 144]
all_grids= [4,5,6]
all_splines= [4,5,6,7]
all_steps = [40,50,100]
all_optimisers = ["Adam"]#["AdamW", "Adam", "SGD", "LFBGS"]
all_weight_decays = [0.001]
all_hidden_units = [128]

[kan] # settings only for KAN networks
all_grids = [2,4,8,12]
all_ks = [1,2,4,6,8,12]
all_lrs = [0.01, 0.001, 0.0001]
all_lambs = [0, 0.01, 0.0001, 0.00001]
all_optimisers = ["LBFGS", "Adam", "SGD"]
all_steps = [15, 30, 50, 72, 100, 200]
all_widths = [2, 3, 4]

[data]
###########################
# Stampa Data
###########################
path = "./data/stampa.csv"
target = "base_diff"
# use for causal features
predictors = [
    "block4a_diff",
    "base_diff",
    "precipitation", 
    "soil_moisture",
    "infiltration",
    "temperature",
    "frost",
    "frost_days",
    "ftc",
    "ftc_days"
]
date = "time"
split_ratio = 0.8
n_lags = 9
start_time = "01-09-2022"


[misc]
verbose = false
label = "stampa"
result_label = "gridOOA"
device = "cuda"
